spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  redis:
    database: 1
    host: 101.200.155.225
    password: JindiRds4Fetcher
    pool:
      max-active: 30
      max-idle: 2
      max-wait: -1
      min-idle: 1
    port: 6379
    timeout: 60000
  datasource:
    url: jdbc:mysql://jindiprismtest.mysql.rds.aliyuncs.com:3306/prism_cq
    username: jindi
    password: jindichangsheng
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 1
      max-idle: 2
      max-active: 2
      max-wait: 20000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
proxy:
  fetchURL: http://39.106.165.35:8001/tydaili


---
spring:
  profiles: online
  redis:
    host: r-2zefa2826e28cca4149.redis.rds.aliyuncs.com
    port: 6379
    password: JindiRds4Fetcher
    timeout: 5000
    database: 1
    pool:
      max-active: 30
      max-wait: 1000
      max-idle: 20
      min-idle: 1
  datasource:
    url: jdbc:mysql://rdsf11umc9ka56o5m38l159.mysql.rds.aliyuncs.com:3306/prism_cq
    username: jindi
    password: jindichangsheng
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 1
      max-idle: 2
      max-active: 2
      max-wait: 20000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
proxy:
  fetchURL: http://172.24.113.240:8001/tydaili